# Generated by Django 5.1.6 on 2025-03-18 20:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_usuario_created_by_admin'),
        ('core', '0002_remove_cantidadperdida_id_perdida_and_more'),
        ('guardar', '0008_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('direccion', models.CharField(blank=True, default=' ', max_length=100)),
                ('telefono', models.CharField(blank=True, default=' ', max_length=20)),
                ('fecha', models.DateTimeField(default=datetime.datetime.today)),
                ('estatus', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardar.producto')),
                ('usuaio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario')),
            ],
        ),
    ]
