# Generated by Django 5.1.6 on 2025-03-18 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        ('guardar', '0008_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='producto',
        ),
        migrations.AddField(
            model_name='order',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guardar.producto'),
        ),
    ]
