# Generated by Django 5.1.6 on 2025-09-09 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_estadocuentausuario'),
        ('core', '0005_comentario'),
        ('guardar', '0019_alter_producto_imagen2_alter_producto_imagen3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='guardar.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario')),
            ],
            options={
                'unique_together': {('producto', 'usuario')},
            },
        ),
    ]
