# Generated by Django 6.0 on 2026-01-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='usuaio',
            new_name='usuario',
        ),
    ]
