# Generated by Django 5.1.6 on 2025-03-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
