# Generated by Django 5.1.6 on 2025-03-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0004_alter_producto_imagen_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
