# Generated by Django 5.1.6 on 2025-03-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usuario_created_by_admin'),
        ('guardar', '0006_remove_usuario_id_nivel_de_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoenespera',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario'),
        ),
        migrations.AlterField(
            model_name='detallescambio',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario'),
        ),
    ]
