# Generated by Django 5.1.6 on 2025-03-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0007_alter_carritoenespera_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='users/usuario.png', null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
