# Generated by Django 5.1.6 on 2025-04-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0008_sugerenciaeliminacion'),
        ('guardar', '0009_producto_is_sale_producto_sale_price'),
    ]

    operations = [
    ]
