# Generated by Django 5.1.6 on 2025-04-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0010_merge_20250406_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
