# Generated by Django 5.1.6 on 2025-05-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0011_remove_producto_sale_price_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='precio de oferta'),
        ),
    ]
