# Generated by Django 5.2.1 on 2025-05-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0012_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen 1'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen 2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen 3'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen 4'),
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
