# Generated by Django 5.1.6 on 2025-05-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0012_producto_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='precio de oferta'),
        ),
    ]
