# Generated by Django 5.1.6 on 2025-05-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0013_alter_producto_sale_price'),
        ('guardar', '0013_remove_producto_imagen_producto_imagen1_and_more'),
    ]

    operations = [
    ]
