# Generated by Django 5.1.6 on 2025-07-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0015_producto_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoenespera',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='carritoenespera',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='compradelproducto',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='detallesdecompra',
            name='id_compra',
        ),
        migrations.RemoveField(
            model_name='detallesdecompra',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='detallesdecompra',
            name='id_proveedor',
        ),
        migrations.RemoveField(
            model_name='detallesdeventa',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='detallesdeventa',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_metodo',
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_usuario',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(default='users/usuario.png', null=True, upload_to='imagenes/', verbose_name='Imagen 1'),
        ),
        migrations.DeleteModel(
            name='CarritoEnEspera',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='CompraDelProducto',
        ),
        migrations.DeleteModel(
            name='DetallesDeCompra',
        ),
        migrations.DeleteModel(
            name='DetallesDeVenta',
        ),
        migrations.DeleteModel(
            name='MetodoDePago',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
