# Generated by Django 5.1.6 on 2025-07-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0016_remove_carritoenespera_id_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerenciaeliminacion',
            name='aceptada',
            field=models.BooleanField(default=False),
        ),
    ]
