# Generated by Django 5.1.6 on 2025-09-09 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0017_sugerenciaeliminacion_aceptada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='like',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Me gusta '),
        ),
    ]
