# Generated by Django 5.1.6 on 2025-09-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0018_producto_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, default='users/usuario.png', null=True, upload_to='imagenes/', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, default='users/usuario.png', null=True, upload_to='imagenes/', verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen4',
            field=models.ImageField(blank=True, default='users/usuario.png', null=True, upload_to='imagenes/', verbose_name='Imagen 4'),
        ),
    ]
