# Generated by Django 5.1.6 on 2025-09-23 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0019_alter_producto_imagen2_alter_producto_imagen3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase2',
            fields=[
                ('id_clase2', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clase2', models.CharField(max_length=50)),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardar.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Clase3',
            fields=[
                ('id_clase3', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clase3', models.CharField(max_length=50)),
                ('id_clase2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardar.clase2')),
            ],
        ),
    ]
