# Generated by Django 5.1.6 on 2025-09-23 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0020_clase2_clase3'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_clase2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guardar.clase2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_clase3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guardar.clase3'),
        ),
    ]
