# Generated by Django 5.1.6 on 2025-09-23 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardar', '0021_producto_id_clase2_producto_id_clase3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_clase3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guardar.clase3'),
        ),
    ]
