# Generated by Django 5.1.6 on 2025-04-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
