# Generated by Django 5.1.6 on 2025-04-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_orderitem_options_orderitem_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordering',
        ),
    ]
