# Generated by Django 5.1.6 on 2025-05-08 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, verbose_name='Método de pago')),
                ('completed', models.BooleanField(default=False, verbose_name='¿Pago realizado?')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de transacción')),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.order', verbose_name='Orden')),
            ],
        ),
    ]
