# Generated by Django 5.1.6 on 2025-05-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date_paid',
        ),
    ]
