# Generated by Django 5.1.6 on 2025-05-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_remove_payment_completed_remove_payment_date_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
