# Generated by Django 5.1.6 on 2025-05-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_remove_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(default='Stripe', max_length=50, verbose_name='Método de pago'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
