# Generated by Django 5.1.6 on 2025-05-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_order_method_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recibido',
            field=models.BooleanField(default=False, verbose_name='¿Recibido?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=15000, verbose_name='Dirección Completa'),
        ),
    ]
