# Generated by Django 5.1.6 on 2025-03-04 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clase', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraDelProducto',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_de_compra', models.DateField()),
                ('id_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.estadoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Perdida',
            fields=[
                ('id_perdida', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.estadoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_de_ingreso', models.DateField()),
                ('existencia', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/')),
                ('id_clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clase')),
                ('id_estado_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.estadoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesDeCompra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.compradelproducto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.detalleproveedor')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CantidadPerdida',
            fields=[
                ('id_c_perdida', models.AutoField(primary_key=True, serialize=False)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('id_perdida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.perdida')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.producto')),
            ],
        ),
        migrations.CreateModel(
            name='SubClase',
            fields=[
                ('id_sub_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sub_clase', models.CharField(max_length=50)),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(default='users/usuari_defecto.jpg', upload_to='users/', verbose_name='imagen de perfil')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Localidad')),
                ('telephone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['-id_usuario'],
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesCambio',
            fields=[
                ('id_cambio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateField()),
                ('tipo_cambio', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.producto')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('fecha', models.DateField()),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.producto')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoEnEspera',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_de_venta', models.DateField()),
                ('id_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.estadoproducto')),
                ('id_metodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.metododepago')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesDeVenta',
            fields=[
                ('id_dt', models.AutoField(primary_key=True, serialize=False)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.venta')),
            ],
        ),
    ]
