# Generated by Django 5.1.6 on 2025-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_cantidadperdida_id_perdida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='Usuario.jpg', upload_to='users/', verbose_name='imagen de perfil'),
        ),
    ]
