# Generated by Django 5.1.6 on 2025-03-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='Usuario.png', upload_to='users/', verbose_name='imagen de perfil'),
        ),
    ]
