# Generated by Django 5.1.6 on 2025-03-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_imagen_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(default='usuario.png', upload_to='users/', verbose_name='imagen de perfil'),
        ),
    ]
