# Generated by Django 5.1.6 on 2025-03-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(default='users/usuario.png', upload_to='users/', verbose_name='imagen de perfil'),
        ),
    ]
