# Generated by Django 5.1.6 on 2025-03-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usuario_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='created_by_admin',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Creado por Admin'),
        ),
    ]
