# Generated by Django 5.1.6 on 2025-03-22 02:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usuario_created_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='pais'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='date_modifile',
            field=models.DateField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='usuario',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='zipcode',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='codigo  postal'),
        ),
    ]
