# Generated by Django 5.1.6 on 2025-03-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usuario_city_usuario_country_usuario_date_modifile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='old_cart',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='carrito antiguo'),
        ),
    ]
