# Generated by Django 5.1.6 on 2025-05-30 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usuario_old_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuentaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitar_eliminacion', models.BooleanField(default=False, verbose_name='Solicitar Eliminación')),
                ('motivo_borrado', models.TextField(blank=True, null=True, verbose_name='Motivo de Borrado')),
                ('fecha_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha de Solicitud')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cuenta', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
